stock_app/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    # url for app
    url(r'', include('stocks_app.urls', namespace='stocks_app')),
]

stocks_app/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'stocks_app'

urlpatterns = [
    # url for Homepage
    url(r'^$', views.index, name='index'),
    # url for Investor Stock Form
    url(r'^stock_form/$', views.stock_form, name='stock_form'),
    # url for Investor Bond Form
    url(r'^bond_form/$', views.bond_form, name='bond_form'),
]

stocks_app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)
    name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()
    last_name = models.CharField(max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class BondTable(models.Model):
    company_stock_symbol = models.TextField(primary_key=True)
    number_of_stocks_owned = models.TextField()
    purchase_price = models.TextField()
    current_price = models.TextField()
    purchase_date = models.TextField()
    bond_coupon = models.TextField()
    bond_yield = models.TextField()
    bond_investor_id = models.IntegerField(db_column='bond_investor_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'bond_table'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    action_flag = models.PositiveSmallIntegerField()

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class InvestorTable(models.Model):
    investor_id = models.AutoField(db_column='investor_ID', primary_key=True)  # Field name made lowercase.
    first_name = models.TextField()
    last_name = models.TextField()
    address = models.TextField()
    phone_number = models.TextField()

    class Meta:
        managed = False
        db_table = 'investor_table'


class StockTable(models.Model):
    company_stock_symbol = models.TextField(primary_key=True)
    number_of_stocks_owned = models.TextField()
    purchase_price = models.TextField()
    current_price = models.TextField()
    purchase_date = models.TextField()
    stock_investor_id = models.IntegerField(db_column='stock_investor_ID')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'stock_table'

stocks_app/forms.py
"""
Author: Tori West
Date: 3/12/2020
Description: Two classes are used to create forms. Each is linked to the models.py
	file by using ModelForm and a Meta class. CharFields are used to decrease the
	size of the input box. However, they are unneccesary and may be removed in the
	future. If they are removed, labels will need to be added to the Meta classes. 
"""

from django import forms

# Import two classes from models.py to link forms to model
from .models import StockTable, BondTable


# Creates form to input new stocks into the StockTable database 
class StockEntry(forms.ModelForm):
	# Added to control the input box size
	stock_investor_id = forms.CharField(label="Enter your Investor ID #", max_length=10)
	company_stock_symbol = forms.CharField(label="Stock Symbol", max_length=10)
	number_of_stocks_owned = forms.CharField(label="Number of Stocks Purchased", max_length=10)
	purchase_price = forms.CharField(label="Purchase Price", max_length=10)
	current_price = forms.CharField(label="Current Price", max_length=10)
	purchase_date = forms.CharField(label="Date you Purchased the Stock(s)", max_length=10)

	class Meta:
		# Set to model class that links to database
		model = StockTable
		fields = ['stock_investor_id', 
			'company_stock_symbol', 
			'number_of_stocks_owned', 
			'purchase_price', 
			'current_price', 
			'purchase_date',
			]


# Creates form to input new bonds into the BondTable database 
class BondEntry(forms.ModelForm):
	# CharField used to shrink input box size
	bond_investor_id = forms.CharField(label="Enter your Investor ID #", max_length=10)
	company_stock_symbol = forms.CharField(label="Bond Symbol", max_length=10)
	number_of_stocks_owned = forms.CharField(label="Number of Bonds Purchased", max_length=10)
	purchase_price = forms.CharField(label="Purchase Price", max_length=10)
	current_price = forms.CharField(label="Current Price", max_length=10)
	purchase_date = forms.CharField(label="Date you Purchased the Bond(s)", max_length=10)
	bond_coupon = forms.CharField(label="Bond Coupon", max_length=10)		
	bond_yield = forms.CharField(label="Bond Yield", max_length=10)

	class Meta:
		# Set to model class that links to database
		model = BondTable
		fields = ['bond_investor_id', 
			'company_stock_symbol', 
			'number_of_stocks_owned', 
			'purchase_price', 
			'current_price', 
			'purchase_date',
			'bond_coupon',
			'bond_yield',
			]

stocks_app/views.py
"""
Author: Tori West
Date: 3/12/2020
Description: After all the necessary imports, three functions are used to request 
	information. The first function pulls data from the database for display through
	the HTML file. The stock_form and bond_form functions are used to save data that
	has been inputted into each form. 
"""

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

# Imported three classes from models.py
from .models import StockTable, InvestorTable, BondTable

# Imported two classes from forms.py
from .forms import BondEntry, StockEntry


# Create your views here.

def index(request):
	"""For Investor Tracking page to pull data from database tables"""
	investorObject = InvestorTable.objects.get(investor_id=1)
	stockObjects = StockTable.objects.all()
	bondObjects = BondTable.objects.all()
	context = {'stocks': stockObjects, 'investor': investorObject, 'bonds': bondObjects}
	return render(request, 'stocks_app/index.html', context)


def stock_form(request):
	"""Form to add new stocks"""
	if request.method != 'POST':
		# No data submitted; create a blank form.
		form = StockEntry()
	else:
		# For submitted data
		form = StockEntry(request.POST)
		if form.is_valid():
			# Form data is cleaned
			investor_id = form.cleaned_data['stock_investor_id']
			symbol = form.cleaned_data['company_stock_symbol']
			stock_number = form.cleaned_data['number_of_stocks_owned']
			purchase_price = form.cleaned_data['purchase_price']
			current_price = form.cleaned_data['current_price']
			purchase_date = form.cleaned_data['purchase_date']
			# Data associated with model class
			stock = StockTable(stock_investor_id=investor_id,
				company_stock_symbol=symbol,
				number_of_stocks_owned=stock_number, 
				purchase_price=purchase_price, 
				current_price=current_price, 
				purchase_date=purchase_date)
			stock.save()
			# Returns user to the main page
			return HttpResponseRedirect(reverse('stocks_app:index'))
			# Identifying new variables
			context = {'stock_investor_id': investor_id,
				'company_stock_symbol': symbol,
				'number_of_stocks_owned': stock_number, 
				'purchase_price': purchase_price, 
				'current_price': current_price, 
				'purchase_date': purchase_date}
			
	context = {'form':form}		
	return render(request, 'stocks_app/stock_form.html', context)


def bond_form(request):
	"""Form to add new bonds"""
	if request.method != 'POST':
		# No data submitted; create a blank form.
		form = BondEntry()
	else: 
		# POST data submitted; process data.
		form = BondEntry(request.POST)
		if form.is_valid():
			form.save()
			# Returns user to the main page
			return HttpResponseRedirect(reverse('stocks_app:index'))
	context = {'form': form}
	return render(request, 'stocks_app/bond_form.html', context)

stocks_app/templates/stocks_app/base.html
<!-- Base page used to define HTML document, create head tags (including meta data, title, and bootstratp css and js links), and navigation. This page is extended to all three pages for consistancy.  -->

{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
	
<head>
  	<meta charset="utf-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  	<title>Stock App</title>
	
	<!-- include bootstrap css and js -->
	{% bootstrap_css %}
	{% bootstrap_javascript %}
</head>

<body style="padding:10px;" >
	<nav class="navbar navbar-default">
		<div class="container navbar-nav" id="navbar">
			<ul class="nav navbar-nav">	
				<li class="nav-item">
					<a class="navbar-brand nav-link" href="{% url 'stocks_app:index' %}">Investor Tracking</a>  
				</li>
				<li class="nav-item">
					<a class="navbar-brand nav-link" href="{% url 'stocks_app:stock_form' %}">Stock Form</a> 
				</li>
				<li class="nav-item">
					<a class="navbar-brand nav-link" href="{% url 'stocks_app:bond_form' %}">Bond Form</a>
				</li>
			</ul>	
		</div>		
	</nav>

<h1>Tracking Investor Stocks and Bonds</h1>

{% block content %}{% endblock content %}
</body>
</html>

stocks_app/templates/stocks_app/bond_form.html
<!-- Bond Form page, which has a form to add bond information to user's database.  -->

{% extends "stocks_app/base.html" %}
{% load bootstrap3 %}

{% block content %}

<br/>
<h2>Enter New Bonds:</h2>

{% if error_message %}
	<p>{{ error_message }}</p>
{% endif %}
<div class="form-group">
<form action="{% url 'stocks_app:index' %}" method='POST'>
	{% csrf_token %}
	{% bootstrap_form form %}
	<button type='submit' name='save' class="btn btn-primary">Add Bond</button>
</form>
</div>


{% endblock content %}

stocks_app/templates/stocks_app/index.html
<!-- Main page used to display investor's stocks and bonds in two tables.  -->

{% extends "stocks_app/base.html" %}

{% block content %}
<br/>
<h2>Stock ownership for {{investor.first_name}} {{investor.last_name}}</h2>

<table style="width:75%" border=1>
	<tr>
		<th>Stock</th>
		<th>Shares</th>
		<th>Purchase Price ($)</th>
		<th>Current Price ($)</th>
		<th>Purchase Date</th>

	</tr>
	
	{% for stock in stocks %}
		<tr>
			<td>{{stock.company_stock_symbol}}</td>
			<td>{{stock.number_of_stocks_owned}}</td>
			<td>{{stock.purchase_price}}</td>
			<td>{{stock.current_price}}</td>
			<td>{{stock.purchase_date}}</td>
		</tr>
		
	{% empty %}
	<p>No stocks found</p>
	{% endfor %}
</table>

<br/>
<p><a href="{% url 'stocks_app:stock_form' %}">Add a New Stock</a></p>

<br/>
<h2>Bond ownership for {{investor.first_name}} {{investor.last_name}}</h2>

<table style="width:85%" border=1>
	<tr>
		<th>Bonds</th>
		<th>Shares</th>
		<th>Purchase Price ($)</th>
		<th>Current Price ($)</th>
		<th>Purchase Date</th>
		<th>Bond Coupon</th>
		<th>Bond Yield</th>


	</tr>
		{% for bond in bonds %}	
		<tr>
			<td>{{bond.company_stock_symbol}}</td>
			<td>{{bond.number_of_stocks_owned}}</td>
			<td>{{bond.purchase_price}}</td>
			<td>{{bond.current_price}}</td>
			<td>{{bond.purchase_date}}</td>
			<td>{{bond.bond_coupon}}</td>
			<td>{{bond.bond_yield}}</td>
		</tr>
	{% empty %}	
	<p>No bonds found</p>
	{% endfor %}
</table>

<br/>
<p><a href="{% url 'stocks_app:bond_form' %}">Add a New Bond</a></p>

{% endblock content %}

stocks_app/templates/stocks_app/stock_form.html
<!-- Stock Form page, which has a form to add new stock information to user's database.  -->

{% extends "stocks_app/base.html" %}
{% load bootstrap3 %}

{% block content %}

<br/>
<h2>Enter New Stocks:</h2>

{% if error_message %}
	<p>{{ error_message }}</p>
{% endif %}
<div class="form-group" size='small' >
<form action="{% url 'stocks_app:index' %}" method='POST'>
	{% csrf_token %}
	{% bootstrap_form form %}
	<button type='submit' name='save' class="btn btn-primary">Add Stock</button>
</form>
</div>

{% endblock content %}